"""BrowserProvider protocol — the vendor- AND transport-agnostic seam.

WHY these methods: a provider adapter's ONLY job is to drive ONE backend (Playwright,
CDP, a remote cloud browser) and return RAW results the engines normalize. Session,
tab, and page handles are opaque strings the provider maps internally — callers never
see a Playwright Page. Because the protocol says nothing about HOW the browser is
reached, a local Playwright adapter and a remote Browserbase adapter are
indistinguishable to the session layer (ADR-017). Mutating verbs return RAW results;
the engines build ActionResult/PageState so gating + normalization live above the SDK.
"""
from __future__ import annotations

from typing import Any, Protocol

from atlas.capabilities.browser.domain.locator import Locator
from atlas.capabilities.browser.providers.capabilities import ProviderCapabilities


class BrowserProvider(Protocol):
    name: str
    is_local: bool
    capabilities: ProviderCapabilities

    # lifecycle
    async def launch(self, *, profile: str | None, incognito: bool,
                     sandbox_spec: Any) -> str: ...          # returns session_id
    async def attach(self, endpoint: str) -> str: ...
    async def health(self, session_id: str) -> bool: ...
    async def close(self, session_id: str) -> None: ...

    # tabs
    async def new_tab(self, session_id: str) -> str: ...     # returns tab_id
    async def list_tabs(self, session_id: str) -> list[str]: ...
    async def close_tab(self, session_id: str, tab_id: str) -> None: ...

    # navigation (read)
    async def goto(self, session_id: str, tab_id: str, url: str) -> None: ...
    async def back(self, session_id: str, tab_id: str) -> None: ...
    async def forward(self, session_id: str, tab_id: str) -> None: ...
    async def reload(self, session_id: str, tab_id: str) -> None: ...

    # DOM / extraction (read) — return RAW; engines normalize
    async def dom_snapshot(self, session_id: str, tab_id: str) -> Any: ...
    async def accessibility_tree(self, session_id: str, tab_id: str) -> Any: ...
    async def query(self, session_id: str, tab_id: str, locator: Locator) -> list[Any]: ...
    async def content_html(self, session_id: str, tab_id: str) -> str: ...
    async def eval_readonly(self, session_id: str, tab_id: str, expr: str) -> Any: ...

    # input (MUTATING — only reached post-gate by the engines)
    async def click(self, session_id: str, tab_id: str, locator: Locator) -> None: ...
    async def type_text(self, session_id: str, tab_id: str, locator: Locator, text: str) -> None: ...
    async def press(self, session_id: str, tab_id: str, key: str) -> None: ...
    async def scroll(self, session_id: str, tab_id: str, x: int, y: int) -> None: ...
    async def submit(self, session_id: str, tab_id: str, locator: Locator) -> None: ...
    async def set_files(self, session_id: str, tab_id: str, locator: Locator,
                        paths: list[str]) -> None: ...

    # media (read)
    async def screenshot(self, session_id: str, tab_id: str, *,
                         full_page: bool, clip: Any | None) -> bytes: ...
    async def pdf(self, session_id: str, tab_id: str) -> bytes: ...

    # network + downloads
    async def start_network_capture(self, session_id: str, tab_id: str) -> None: ...
    async def drain_network_events(self, session_id: str, tab_id: str) -> list[Any]: ...
    async def await_download(self, session_id: str, tab_id: str) -> tuple[str, str]: ...  # (path, url)

    # storage / cookies (read+write; writes gated by engines)
    async def get_cookies(self, session_id: str) -> list[Any]: ...
    async def set_cookies(self, session_id: str, cookies: list[Any]) -> None: ...
    async def get_storage_state(self, session_id: str) -> Any: ...   # for 6.2 session persistence
    async def set_storage_state(self, session_id: str, state: Any) -> None: ...
