"""Location provider protocol: geocode (address -> lat/lon) + country_info."""

from __future__ import annotations

from typing import Any, Protocol

from atlas.capabilities.domain.location import CountryInfo, GeocodeResult
from atlas.capabilities.providers.base import CapabilityRequest, RetryPolicy
from atlas.capabilities.registry.capability import Capability


class LocationProvider(Protocol):
    name: str
    capability: Capability
    is_local: bool
    requires_auth: bool

    async def initialize(self) -> None: ...
    async def authenticate(self) -> None: ...
    async def health(self) -> bool: ...
    async def geocode(self, query: str) -> GeocodeResult | None: ...
    async def country_info(self, country: str) -> CountryInfo | None: ...
    async def execute(self, request: CapabilityRequest) -> Any: ...
    def normalize(self, raw: Any) -> Any: ...
    def retry_policy(self) -> RetryPolicy: ...
    async def shutdown(self) -> None: ...
