"""Transport-independent Trust Center application facade."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from atlas.interfaces.api.schemas_trust import (
    ApprovalDecisionCommand,
    ApprovalView,
    AuditEventView,
    AuditPage,
    MemoryCorrectionCommand,
    MemoryFactView,
    MemoryMutationReceipt,
    ProvenanceView,
    TaskPage,
    TaskView,
)


class AtlasTrustPlane(Protocol):
    async def list_tasks(self, *, cursor: str | None, limit: int) -> TaskPage: ...
    async def get_task(self, task_id: str) -> TaskView: ...
    async def pending_approvals(self) -> Sequence[ApprovalView]: ...
    async def get_approval(self, approval_id: str) -> ApprovalView: ...
    async def decide_approval(self, command: ApprovalDecisionCommand) -> ApprovalView: ...
    async def search_memory(self, query: str, *, limit: int) -> Sequence[MemoryFactView]: ...
    async def get_memory_fact(self, fact_id: str) -> MemoryFactView: ...
    async def memory_provenance(self, fact_id: str) -> Sequence[ProvenanceView]: ...
    async def correct_memory(self, command: MemoryCorrectionCommand) -> MemoryMutationReceipt: ...
    async def supersede_memory(
        self, fact_id: str, *, idempotency_key: str, request_id: str,
    ) -> MemoryMutationReceipt: ...
    async def delete_memory(self, fact_id: str, *, idempotency_key: str, request_id: str) -> MemoryMutationReceipt: ...
    async def audit(self, *, task_id: str | None, correlation_id: str | None,
                    execution_id: str | None, cursor: str | None, limit: int) -> AuditPage: ...
    async def audit_event(self, event_id: str) -> AuditEventView: ...
